# Generated by Django 5.1.2 on 2024-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dlc_count', models.IntegerField()),
                ('header_image', models.CharField(max_length=100)),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('achievements', models.IntegerField()),
                ('developers', models.TextField(null=True)),
                ('publishers', models.CharField(max_length=255, null=True)),
                ('categories', models.TextField(null=True)),
                ('genres', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
